# Generated by Django 6.0.2 on 2026-02-18 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pallet_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EanCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean_code', models.CharField(max_length=64, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ean_codes', to='core.product')),
            ],
        ),
    ]
